// Generated by CoffeeScript 1.3.1
(function() {

  this.socket = io.connect("http://localhost:1337");

  this.socket.on("init", function(data) {
    return console.log("init", JSON.stringify(data));
  });

  this.socket.on("update", function(data) {
    return console.log("update", JSON.stringify(data));
  });

}).call(this);
